# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# RENIEC API Configuration
RENIEC_API_URL=https://dniruc.apisperu.com/api/v1/dni
RENIEC_API_TOKEN=

# RENIEC API Fallback 1 - decolecta.com
RENIEC_API_URL_FALLBACK=https://api.decolecta.com/v1/reniec/dni
RENIEC_API_TOKEN_FALLBACK=

# RENIEC API Fallback 2 - consultasperu.com
RENIEC_API_URL_FALLBACK2=https://api.consultasperu.com/api/v1/query
RENIEC_API_TOKEN_FALLBACK2=
